### ISSUE TITLE
Cannot run in 4.1.0 redmine

### ISSUE THREAD

**Issue by CNPF** [HugoHasenbein/redmine_attachment_categories#4]
I try to update your plugin. 

I attached a diff file.
Migrate is ok but i have a error when to save a categorie.
I don't undestrand the problem.

App 30882 stderr: Started PATCH "/redmine/attachment_categories/1" for 90.108.47.151 at 2020-01-08 08:03:20 +0000
App 30882 stderr: Processing by AttachmentCategoriesController#update as HTML
App 30882 stderr:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"guQUaVI/Ih+ZEJpnB4VEJ3+CJ+OaHfZgGGmdJ3pNMVe8ht3Xqhyz6BB8MK9C4JnrY7xXYUXc0IhnuqCndVvN7A==", "attachment_category"=>{"name"=>"Confidentiel", "html_color"=>"#FFCCCC"}, "commit"=>"Sauvegarder", "id"=>"1"}
App 30882 stderr:   Current user: user.name (id=11)
App 30882 stderr: Completed 500 Internal Server Error in 6ms (ActiveRecord: 2.3ms)
App 30882 stderr:
App 30882 stderr: ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
App 30882 stderr:
App 30882 stderr: plugins/redmine_attachment_categories/app/controllers/attachment_categories_controller.rb:59:in `update'
App 30882 stderr: lib/redmine/sudo_mode.rb:65:in `sudo_mode'
[redmine_attachment_categories_r4.1.0.diff.txt](https://github.com/HugoHasenbein/redmine_attachment_categories/files/4034125/redmine_attachment_categories_r4.1.0.diff.txt)

**Comment by CNPF** [comment]
fix all problems using https://github.com/mukkoo/redmine_attachment_categories/tree/4x_compatibility
